alias i='doas apt install'
alias reboot='doas systemctl reboot'
alias poweroff='doas systemctl poweroff'
alias sucode='doas code $1 --user-data-dir='"'"'/root/.config/Code - OSS/'"'"' --no-sandbox'
alias l='ls -al $LS_OPTIONS'
